### ISSUE TITLE
Not SSR compatible

### ISSUE THREAD

**Issue by darkiron** [lokyoung/vuejs-paginate#100]
Hi,
In server side rendering we got an error: 
```js
ReferenceError: window is not defined
```

**Comment by lokyoung** [comment]
Hi @darkiron . If you want to use SSR, you need to import this library follow this method.
```js
import Paginate from 'vuejs-paginate/src/components/Paginate.vue';
```

**Comment by lokyoung** [comment]
@darkiron I will close this issue now. Any questions please reopen it.

**Comment by jamesalways** [comment]
@lokyoung can you add this in the docs? In my opinion is important the docs has this info. Thanks!
