### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by betweenbrain** [lokyoung/vuejs-paginate#101]
I was unable to find this documented anywhere, but is it possible to customize the layout of this component somehow? That is, for example, could the previous and next buttons be after the list of pages?

**Comment by lokyoung** [comment]
Hi @betweenbrain , sorry currently we don't provide any way to customize the layout. But if you want to move the previous and next buttons after the list of pages, you can put the html content of previous and next buttons in `last-button-text`,
