### ISSUE TITLE
why not use src in <a> link

### ISSUE THREAD

**Issue by bimohxh** [lokyoung/vuejs-paginate#103]
I find this component only has `click-handler` click event, why just add link like `<a src="xxxxxx?page=1"></a>` ? this will lead a good SEO.

**Comment by lokyoung** [comment]
Hi @bimohxh  , firstly i don't think `src` is valid in `a` tag, i think what you mean is `href`. Secondly adding `href` and click will change the url in SPA which may bring unexpected behavior.

**Comment by fjeddy** [comment]
SPA does not mean "no links"... Most SPA's today uses links so you can go back to the specific page and or bookmark a page.

This shouldn't be closed and is def. a +1 from me.

**Comment by mirzaevra** [comment]
Hey. Add the ability to add an attribute href. For ssr it is very necessary.

**Comment by aavrug** [comment]
The href option should be there in the configuration which will be really helpful for SSR. Not sure why this is still not supported. Can you please consider this?
