### ISSUE TITLE
请问如何在页面上直接调用该组件，不需要webpack打包的那种

### ISSUE THREAD

**Issue by 18823752727** [lokyoung/vuejs-paginate#11]

**Comment by lokyoung** [comment]
谢谢建议，会加一个PR处理这个问题

**Comment by lokyoung** [comment]
在html中引入`<script src="https://unpkg.com/vuejs-paginate@latest"></script>`

注册组件
```js
Vue.component('paginate', VuejsPaginate)
```

然后就可以正常使用了，欢迎反馈，感谢！

**Comment by lokyoung** [comment]
@18823752727 如果还有疑问请重新open这个issue。先关闭了。
