### ISSUE TITLE
How to hide first-last-button ?

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [lokyoung/vuejs-paginate#113]
Hello! Thank you for nice plugin! It's really useful. I see ability to hide prev/next buttons. But what about `hide-first-last`? Is it implemented and I've missed it? Or you are planning to make this feature? Thank you again). 
I would like to have something like this:

    <paginate
        :page-count="10"
        :click-handler="functionName"
        :prev-text="'<'"
        :next-text="'>'"
        :page-class="'page-item'"
        :container-class="'pagination'"
        :page-link-class="'page-link'"
        :prev-link-class="'page-link'"
        :next-link-class="'page-link'"
        :first-last-button="true"
        :first-button-text="'<<<'"
        :last-button-text="'>>>'"
        :hide-prev-next="true"
        :hide-first-last="true"
    >
    </paginate> 

Please see on the last line of params. ` :hide-first-last="true"`

**Comment by lokyoung** [comment]
@Aleksej-Shherbak Please check `first-last-button`. Thanks.

**Comment by Aleksej-Shherbak** [comment]
> @Aleksej-Shherbak Please check `first-last-button`. Thanks.

Thanks for answer, but maybe I don't understand you. My question was: Is it possible to hide the first button (not disable, exactly hide) if I on the first page and is it possible to hide the last button if I on the last page. I will show you a screen. 
![Снимок экрана от 2019-10-21 12-07-06](https://user-images.githubusercontent.com/12964099/67192211-d9ec6580-f3fb-11e9-9caa-9e0a47a4d8fd.png)

Thank you again!
