### ISSUE TITLE
Prevent default

### ISSUE THREAD

**Issue by Fleeck** [lokyoung/vuejs-paginate#13]
Hello, when I try to click on another page I am being redirected to home because of `href='#'`. And I have no access to the event object on the clickHandler. How can I call preventDefault on this?

**Comment by lokyoung** [comment]
Hello @Fleeck . Thanks for feedback. I use `href='#'` to match the style of bootstrap4. But i just like you mentioned, it not appropriate. I have add new pr to handle that.

**Comment by lokyoung** [comment]
Also about the `clickHandler`. The parameter of the `clickHandler` is the number of selected page. I think you don't need `preventDefault` after i remove `href='#'`. But if there is any problems, please feel free to ask. Thanks.

**Comment by lokyoung** [comment]
Please try new version `0.7.0` to see if it solves you problems. Thank you very much.

**Comment by Fleeck** [comment]
Thanks!

**Comment by lokyoung** [comment]
@Fleeck Thanks i will take it into consideration.

**Comment by lokyoung** [comment]
@Fleeck Please try `0.7.1`. I just set it as the default style of `a` in this component. Thanks.

**Comment by Fleeck** [comment]
Thanks, works as expected.
