### ISSUE TITLE
add a prop for <li> and <a> class

### ISSUE THREAD

**Issue by marsPure** [lokyoung/vuejs-paginate#2]
Thank you for creating this project, I want to add [bootstrap 4 pagination](http://v4-alpha.getbootstrap.com/components/pagination/) classes to the component and I have to pass class names to `<li>` and `<a> ` too, can you please add optional props for those tags?

PS: or I can submit a pr if you think it is a good idea.

**Comment by lokyoung** [comment]
Hi @marsPure , many thanks for the review. I will make some changes add add i PR soon then we can review it together.

**Comment by lokyoung** [comment]
Hello @marsPure . You can check the changes in the PR. Also you can run the demo by clone the project and run `npm install` then `npm run demo`. I have published a new version v0.3.0 with the latest changes. Thanks.

**Comment by marsPure** [comment]
it works great, thank you so much. one more small issue for me was Bootstrap 4 overwrite the link color if the href doesn't exist so it won't be blue. I am not sure if you want to add this to your whole package or not, so I forked it. thank you so much for responding so quickly.
