### ISSUE TITLE
Cannot change CSS inside the pagination component !!

### ISSUE THREAD

**Issue by thegreyfellow** [lokyoung/vuejs-paginate#20]
## The problem:

I can only change the css of the pagination (class of the component). but I can't change the css of the `li` or `a` or `a .active`. I tried to put the css in a not scoped or a scoped component I even put it inside the body not scoped css file but it didn't work I added the properties `pageClass` and `pageLinkClass` and tried the same thing but still the sam result.

## What should happend:

I should be able to change the style of the pagination component with this code:

```javascript

<template>
                 .
                 .
                 .
                <div class="my-pagination col-md-offset-3 col-sm-offset-2 col-xs-offset-1">
                  <paginate
                    v-if="numberOfPages > 1"
                    :pageCount="numberOfPages"
                    :clickHandler="getPageData"
                    :prevText="'préc.'"
                    :nextText="'Suiv.'"
                    :containerClass="'pagination'"
                    :pageClass="'page-item'"
                    :pageLinkClass="'page-link-item'">
                  </paginate>
                </div>
                 .
                 .
                 .
</template>
<script>
</script>
...
<style>
                 .
                 .
                 .
    .pagination {
      margin: 5% 25%; // this works
      .page-item {
        .page-link-item .active {
          border-radius: 0px; // this don't work
          position: static !important; // this don't work
          background-color: #ed6528 !important; // this don't work
        }
      }
    }
                 .
                 .
                 .
</style>
```

**Comment by lokyoung** [comment]
Hello @thegreyfellow . Could you please change your css like this to see if solves your issue?
```css
.pagination {
  margin: 5% 25%;
}

.page-item.active {
  border-radius: 0px;
  position: static !important;
  background-color: #ed6528 !important;
}
```

**Comment by thegreyfellow** [comment]
I tried that too before I came here and I did try it now but still the same result. it doesn't even get detected by the browsers inspector like it does for the `.pagination` class:

![image](https://cloud.githubusercontent.com/assets/16798435/24080529/5a2adfee-0c99-11e7-9b65-781a1a582b74.png)

as for the `.page-item` or `.page-link-item` classes they don't appear in the inspector.

![image](https://cloud.githubusercontent.com/assets/16798435/24080549/a2af8f12-0c99-11e7-9fa2-4b8bf42d802c.png)

**Comment by lokyoung** [comment]
@thegreyfellow I have created an example using your css. It works well. You can check the (demo)[https://jsfiddle.net/lokyoung/vacq6xzt/]. Thanks!

**Comment by thegreyfellow** [comment]
I'm sorry but the jsfiddle link doesn't seem to work for me. when I add up my css can you re check please.

https://jsfiddle.net/t0bunxax/
![image](https://cloud.githubusercontent.com/assets/16798435/24080796/d4a46b06-0c9d-11e7-9e94-fd56cdadbc9d.png)

**Comment by lokyoung** [comment]
Could you please try my demo again? It works well i guess.
https://jsfiddle.net/lokyoung/vacq6xzt/
<img width="540" alt="screen shot 2017-03-19 at 8 21 41 pm" src="https://cloud.githubusercontent.com/assets/14074079/24080837/b9386536-0ce1-11e7-94c5-980b4a99f7db.png">

**Comment by thegreyfellow** [comment]
Thank you but I tried my best and didn't find a solution to my problem. I would've shared the base code if it weren't private, finally I used the library as a component and modified the styles inside the component and that made it work for me, also I had a problem with modals the pagination `.active` page button was always overlaying on the modals it has the position relative that should be set to static instead that's how it worked for me. I'm still not sure if this is an issue of the library or in my code I let you choose to close the issue or not, and thank you for your help @lokyoung :+1:

**Comment by lokyoung** [comment]
Hello @thegreyfellow . You can check the README of the component. You can run the demo to have a better understanding.
https://github.com/lokyoung/vuejs-paginate#demo

In the jsfiddle you sent(https://jsfiddle.net/t0bunxax/). You can change `:pageClass` to `:page-class`, `:pageLinkClass` to `:page-link-class`. And see if it's ok. Seems the props need to be written like this format without vue template.

And feedback is welcome. Thank you very much.

**Comment by martinnaughton** [comment]
I also have the same issue. Even in the style console it does not show the css selectors i used. It does in the html element show the class being used but no CSS is rendered in the style console. 

I copied the example exactly out of jsfiddle and it did not render properly like in jsfiddle.

Using chrome 65 and firefox 45 and Vuejs 2.5.2.

This is the second link on google when searching for a fix to this issue.

When i add this link to the top of index.html page it renders as a bootstap pagination style.  this is because bootrap has a pagination css class that access all the elements underneath the elements. 
<link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.css">

```
.pagination {
  display: inline-block;
  padding-left: 0;
  margin: 20px 0;
  border-radius: 4px;
}
.pagination > li {
  display: inline;
}
.pagination > li > a,
.pagination > li > span {
  position: relative;
  float: left;
  padding: 6px 12px;
  margin-left: -1px;
  line-height: 1.42857143;
  color: #337ab7;
  text-decoration: none;
  background-color: #fff;
  border: 1px solid #ddd;
}

```

**Comment by martinnaughton** [comment]
Just tested with a new project with just vuejs-paginate included. There is css changes for any thing but pagination class. I thought it might be bootstrap in my project but this project does not have any bootstap included. 

https://github.com/martinnaughton/vuejs-paginate-test

**Comment by Zicrael** [comment]
Same for me. Its not work correctly in real life projects. In jsfiddle yes, but not in live vue project.

**Comment by javiscript13** [comment]
It works for me if I put the css in a not scoped style section.
