### ISSUE TITLE
为何使用require.js加载js库无法使用？如图

### ISSUE THREAD

**Issue by allan2coder** [lokyoung/vuejs-paginate#21]
![Uploading E`G0C05$7(@RT)CL((VSC%M.png…]()

![10](https://cloud.githubusercontent.com/assets/14307551/24179531/99dbb75a-0eea-11e7-9420-5c7c77f1c10e.png)
![11](https://cloud.githubusercontent.com/assets/14307551/24179532/9a0faeb6-0eea-11e7-851f-2918338d2736.png)

**Comment by lokyoung** [comment]
你没有使用vue模板，如果直接使用的话需要改下props的名称格式。改成camel case就可以使用了。
```html
<paginate
  :page-count="20"
  :page-range="3"
  :margin-page="2"
  :container-class="'pagination'">
</paginate>
```
我会在接下来的更新中完善下这个问题。Thanks for you feedback!

**Comment by allan2coder** [comment]
非常感谢！可以了。

**Comment by lokyoung** [comment]
也感谢你的反馈。关闭这个问题了。有问题再提issue。
