### ISSUE TITLE
点击事件如何返回当前pageNum?

### ISSUE THREAD

**Issue by allan2coder** [lokyoung/vuejs-paginate#22]
`clickHandler	Function	The method to call when page clicked. Use clicked page number as parameter.`

但没写点击具体页码或上下页如何返回当前页码参数？

**Comment by lokyoung** [comment]
https://github.com/lokyoung/vuejs-paginate#usage
README中有一个example
clickHandler方法的参数就是当前pageNum
```js
clickCallback (pageNum) => {
  console.log(pageNum)
}
```
你可以查看本项目的[online demo](https://jsfiddle.net/lokyoung/u3u3nzns/)

**Comment by allan2coder** [comment]
![Uploading 111111.png…]()
就是这么写的，为何点击后无效？
上下一页也不生效

require.js中引用的js是这个目录下的应该跟这个无关吧？
![Uploading _](HFBZ_76~H]TXG32N%V]M.png…]()

**Comment by allan2coder** [comment]
还是属性问题，需要改为
`:click-handler="clickCallback"`就好了。为啥不能大写？

**Comment by lokyoung** [comment]
@allan2coder 如果你使用vue template，或者把内容写在template property里。是可以使用camel case的。但是直接使用会受规定限制。我会在下面的版本中调查这个问题。

**Comment by lokyoung** [comment]
@allan2coder https://cn.vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case
这里给出了答案

**Comment by allan2coder** [comment]
@lokyoung 感谢。

**Comment by lokyoung** [comment]
@allan2coder 非常感谢你的反馈。我在README中也更新了kebab-case的用法。在vue template中camelCase和kebab-case都是可以使用的。但是在html中，只能使用kebab-case。
https://github.com/lokyoung/vuejs-paginate#in-html
