### ISSUE TITLE
Prev and Next Button Should Be Disabled.

### ISSUE THREAD

**Issue by ttpham0111** [lokyoung/vuejs-paginate#26]
The Prev and Next button should be disabled when the page is 1 and last, respectively.

**Comment by lokyoung** [comment]
Hello @ttpham0111 . Thank you very much for this feedback. I have added a PR for this issue. And publish a version. You can try `v0.9.0`. Hope it solves your problems.

**Comment by lokyoung** [comment]
Hello @ttpham0111 . I will close this issue now. If any problems, please reopen it. Thanks.
