### ISSUE TITLE
How to reset pagination when page-count changes

### ISSUE THREAD

**Issue by kiwo12345** [lokyoung/vuejs-paginate#29]
When I first init the pagination I pass this `:page-count="nPages"`

Now lets say that I browse 3 pages and make a new search and my server only returns 1 page. Then `nPages` will be set to 1 and the pagination components changes to only display 1 page.

But it will not mark the 1 page `active` and I can still click both prev and next.

How to reproduce:

Init the pagination with a dynamic page-count
` :page-count="nPages"`

Lets say that `nPages` is 3. So 3 pages will show up in the pagination.
Now click on page 3 and change `nPages` like:

`$vm0.nPages = 1;`

**Update**
Each time I post a new search to my server and and the result is not `0` I reset the pagination by:
`this.$refs.paginate.selected = 0` It seems to work but I am not sure this is the right way to do it

**Comment by lokyoung** [comment]
Hello @kiwo12345 .You're right. Now you can manually reset by `this.$refs.paginate.selected`. Not sure if i need to provide another way in the future. But i will take it into consideration. Thank you very much.

**Comment by kiwo12345** [comment]
@lokyoung Okey, thanks for the info!
