### ISSUE TITLE
动态改变page-count、如何将页码激活状态重置为第一页?

### ISSUE THREAD

**Issue by allan2coder** [lokyoung/vuejs-paginate#30]
动态改变page-count、如何将页码激活状态重置为第一页?

**Comment by lokyoung** [comment]
@allan2coder `this.$refs.paginate.selected = 0`

**Comment by allan2coder** [comment]
![r82 1dz4ot 3 197avbf6q](https://cloud.githubusercontent.com/assets/14307551/26149158/d5e325b8-3b2b-11e7-8df2-b6ef6771a71e.png)

以上是我的代码，请我我是在获取page-count后加上`this.$refs.paginate.selected = 0`这段代码吗？

**Comment by lokyoung** [comment]
@allan2coder 在你需要把重置为第一页的时候加上就行了。

**Comment by allan2coder** [comment]
![way2aafz v 0 u dm 5rl q](https://cloud.githubusercontent.com/assets/14307551/26149326/79739d20-3b2c-11e7-82f2-8c52e4761811.png)
会出现该报错

**Comment by allan2coder** [comment]
好了。感谢。
