### ISSUE TITLE
If using as a subcomponent, scoped styling does not work

### ISSUE THREAD

**Issue by cgs** [lokyoung/vuejs-paginate#31]
I have a parent component which uses Paginate as a subcomponent:

```
<script>
  import Paginate from 'vuejs-paginate/dist'

  export default {
    components: {
      Paginate
    },
    ...
</script>
```

Also in parent component:

```
<style lang="scss" scoped>
.page-item.active a {
  color: red;
}
</style>
```
This does not work when attempting to style pagination. Removing "scoped" does however:

```
<style lang="scss">
...
</style>
```

Looks like this is a [Vue issue](https://github.com/vuejs/vue-loader/issues/661), but I hope this helps someone.

**Comment by lokyoung** [comment]
Hello @cgs . Seems Vue core team is going to working on this issues. So much thanks for this feedback.

**Comment by lokyoung** [comment]
@cgs Now `vue-loader` can solve this issue.
https://github.com/vuejs/vue-loader/releases/tag/v12.2.0
