### ISSUE TITLE
Next Page button stays active when page-count is 0

### ISSUE THREAD

**Issue by zmeiPop** [lokyoung/vuejs-paginate#34]
Next Page button stays active when page-count is 0 due to following logic
Original Code
`
lastPageSelected() {
      return this.selected === this.pageCount - 1
    }
`
Potential fix
`lastPageSelected() {
      return this.selected >= this.pageCount
    }`

**Comment by lokyoung** [comment]
Hello @zmeiPop . So much thanks for this feedback. These days i'm too busy. So reply so late. Sorry for that.
Actually it should be `return (this.selected === this.pageCount - 1) || (this.pageCount === 0)`.
I will publish in the next version.

**Comment by zmeiPop** [comment]
Thank you. Closing issue.

**Comment by lokyoung** [comment]
@zmeiPop You can try the latest release 'v0.9.1'. Any problems just contact me.
