### ISSUE TITLE
No li around items

### ISSUE THREAD

**Issue by stygiansabyss** [lokyoung/vuejs-paginate#35]
Is it possible to have an option to disable the `li` wrapping?  When this happens, use the `a` tag for adding disabled to?

In semantic-ui, there is no `li` wrapper around the links.  So this breaks the disabled that is added by your component.

Thanks!

**Comment by lokyoung** [comment]
@stygiansabyss Sorry for reply so late. I have publish a new version `v1.0.0` which included this support. You can add a new attribute `no-li-surround`, and set it to `true` to remove`li`. You can check the demo in `./demo/App.vue`. I have test it with semantic-ui, and it works well. Thanks

**Comment by stygiansabyss** [comment]
Wonderful!  Thank you!

**Comment by lokyoung** [comment]
@stygiansabyss I will close this issue for now. Any questions just reopen it. Thanks!
