### ISSUE TITLE
Add prop for initially selected page

### ISSUE THREAD

**Issue by RossOliver87** [lokyoung/vuejs-paginate#4]
This is a useful component however I've found myself in a situation where I want to be able to start on a page that isn't the first page - would it be possible to add a prop to allow the initial page to be changed?

Thanks!

**Comment by lokyoung** [comment]
Hello @RossOliver87. I have push the updates with setting the initial page. You can check the `README.md`, and you will found that it has a new prop called `initialPage`. You can use this by install the latest version v0.4.0.

**Comment by RossOliver87** [comment]
@lokyoung works great - appreciate you adding this so quickly!

**Comment by lokyoung** [comment]
@RossOliver87 Thanks for your advice. Please feel free to add issues for this project. Thank you very much.
