### ISSUE TITLE
Custom class for active item?

### ISSUE THREAD

**Issue by hotrush** [lokyoung/vuejs-paginate#40]
Feature request for custom class for active item (a and li)

**Comment by lokyoung** [comment]
@hotrush Sorry for replying so late. So busy these days. Maybe you can try to add your custom style on 'active' class. I will check it when i got a chance. Thanks.

**Comment by lokyoung** [comment]
@hotrush I have published a new version `v1.3.0`. You can try the `active-class` to set the class name. Sorry for delay.

**Comment by hotrush** [comment]
@lokyoung thanks, will try

**Comment by lokyoung** [comment]
@hotrush I will close this issue for now. Any problems just reopen it. Thanks.
