### ISSUE TITLE
2 paginations on the same page ( in sync)

### ISSUE THREAD

**Issue by swinyx** [lokyoung/vuejs-paginate#43]
2 or more pagination components on the same page don't get synced.
I have a page with 50 entries per page displayed and I want to have a pagination at the top and at the bottom ( to make it more accessible to the user, instead of having to scroll all the way to see the pagination links).
When I add 2 components, the page numbers are off ( they don't highlight the current page at the same time). Please help

**Comment by lokyoung** [comment]
Hello @swinyx . You can check this issue https://github.com/lokyoung/vuejs-paginate/issues/36 . I think it will solve your issue. Any questions just reopen this issue.
