### ISSUE TITLE
Can this be made server-side compatible by removing references to window and document objects?

### ISSUE THREAD

**Issue by sbefort** [lokyoung/vuejs-paginate#44]
Please see this issue that has just been updated:
https://github.com/lokyoung/vuejs-paginate/issues/32

**Comment by lokyoung** [comment]
Hello @sbefort . Sorry for replying so late. Have some personal stuff these days. The `window` is generated by the build script. Will try to find a solution. Hope this component works well in your project.

**Comment by sbefort** [comment]
The component works very well so thank you for that.  Many people are using server-side rendering tools like [Nuxt](https://medium.com/@devlob/handling-server-side-rendering-and-seo-with-nuxt-js-fa8a2b0ae2ee) for SEO purposes so if you could make it server-side compatible by somehow getting rid of client-side objects like `window` and `document` that would be awesome.

**Comment by kmsheng** [comment]
I built successfully without `window` and `document` by removing the style tag of `Paginate` https://github.com/lokyoung/vuejs-paginate/blob/master/src/components/Paginate.vue#L215-L219

**Comment by sbefort** [comment]
Thanks I'll check it out!

**Comment by johnRivs** [comment]
In Nuxt (or SSR in general) when you set this plugin to not happen in the server, errors referencing `window` not being available are gone but you get this instead:
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by lokyoung** [comment]
@johnRivs Thank you so much.
@sbefort You can import the library by `import Paginate from 'vuejs-paginate/src/components/Paginate';` for SSR. Any question please reopen this issue.
