### ISSUE TITLE
next and prev button hide

### ISSUE THREAD

**Issue by ayaz323** [lokyoung/vuejs-paginate#45]
Hey thanks for this component, but How Can I hide prev and next button when I have one item,

**Comment by lysek** [comment]
I used CSS to hide prev and next buttons:
```
:next-class="'hidden'"
:prev-class="'hidden'"
```

**Comment by Falcornus** [comment]
I think would be better just hide pagination when you have only 1 item

**Comment by lokyoung** [comment]
@ayaz323 @lysek @Falcornus Hey guys, sorry for the delay. You can try the `v1.7.0` version. I have added a new prop called `hide-prev-next`. It will hide prev/next button when there is no previous or next page. Any questions please reopen this issue. Thanks.
