### ISSUE TITLE
Dots bug

### ISSUE THREAD

**Issue by MisterGrump** [lokyoung/vuejs-paginate#50]
Hey guys! I encountered such a problem that when combined, as in the example below, the button with dots is not added at the beginning, but on the last page everything is fine.

https://jsfiddle.net/MrGrump/u3u3nzns/175/

**Comment by lokyoung** [comment]
Hello @MisterGrump . Thanks for the feedback. I found some bugs in my current source code. Have fixed and publish. You can try `v1.4.0`. I have made some little changes in `page-range`, now it will show the range count around the selected page. Which means you set it to `2`, and you select the first page, It will show the second and the third page. Thanks. 
```html
 <paginate 
      :page-count="6"
      :page-range="2"
      :margin-pages="2"
      :containerClass="'pagination'"
      :clickHandler="clickCallback">
    </paginate>
```

**Comment by lokyoung** [comment]
@MisterGrump I will close the issue for now. Any problems you can reopen it. Thanks.
