### ISSUE TITLE
Add .babelrc file to .npmignore

### ISSUE THREAD

**Issue by hamzehdoostie** [lokyoung/vuejs-paginate#53]
Hi,

I am trying to use this for ssr.  To work around https://github.com/lokyoung/vuejs-paginate/issues/44, I import it like this:

`import Paginate from 'vuejs-paginate/src/components/Paginate';`

The problem is I also use babel in my project, and your `.babelrc` file is getting used by my babel.

If you add `.babelrc` to `.npmignore` that would fix this.

Thanks

**Comment by lokyoung** [comment]
Hi @hamzehdoostie . The `.babelrc` in the project is also used for test plugins. Did you find a way to solve your issue? Sorry for replying sooooooooo later.

**Comment by lokyoung** [comment]
@hamzehdoostie Any problems just reopen this issue. I will close it for now. Thanks.
