### ISSUE TITLE
safari page error

### ISSUE THREAD

**Issue by liaohainan** [lokyoung/vuejs-paginate#54]
在safari浏览器里打开的时候，总是出现第一页然后最后一页，然后是第二页，最后是倒数第二页
<paginate
            v-if="pageShow"
            :page-count="pageNo"
            :page-range="4"
            :click-handler="pageCallBack"
            ref="paginate"
            :prev-text="'上一页'"
            :next-text="'下一页'"
            :initial-page="pages"
            :container-class="'pagination clear'">
          </paginate>

**Comment by lokyoung** [comment]
@liaohainan 有更详细的描述或者截图么

**Comment by liaohainan** [comment]
我已经解决了，我提了个pr，麻烦您看一下，就是因为safari在遍历对象的时候没有默认排序，而您是第二步就添加了总页数

**Comment by liaohainan** [comment]
顺序是1，7，2，3，4，5，6，。。。这样一个顺序

**Comment by lokyoung** [comment]
@liaohainan 抱歉最近比较忙，一直没有处理。刚刚合并并且发布了，可以使用新版`v1.5.0`。有任何问题可以随时reopen这个issue。
