### ISSUE TITLE
missing disabled-class 

### ISSUE THREAD

**Issue by mromanoff** [lokyoung/vuejs-paginate#56]
vuejs-paginate has a property to set custom active class. ``:active-class="paginate__item--active"``
```active-class | String | CSS class name for active page element. default: active```
but in there is not way to set disabled. In my case i need it for prevContent and nextContent elements. something like this ``:disabled-class="paginate__item--disabled"``

**Comment by lokyoung** [comment]
@mromanoff Sorry for the delay. You can try this feature in `v1.5.1`. Any problems please reopen this issue. Thanks.
