### ISSUE TITLE
Keep two paginations in sync

### ISSUE THREAD

**Issue by juniorgarcia** [lokyoung/vuejs-paginate#59]
We have two paginations: one on the top of a table, another one at the end. We must keep them in sync. I believe that exposing the `selected` property can help to achieve this and don't compromise the structure of the component.

Is there another way to do so?
Is this something you can consider to do?

Thanks!

**Comment by lokyoung** [comment]
Hi @juniorgarcia . Now maybe we can only set the selected pages by `$refs`. You can check #36 .
I'm still thinking of if there is a better way. Sorry for the delay. Thanks for you suggestion.

**Comment by lokyoung** [comment]
Hi @juniorgarcia . You can use `v-model` to keep them in sync by passing the same object. Please upgrade to `v2.0.0` and have a try. Thanks!
