### ISSUE TITLE
Using <span> instead of <a>

### ISSUE THREAD

**Issue by ecmel** [lokyoung/vuejs-paginate#6]
Hi, thanks for the nice work.

Is it possible to use `<span>` tag instead of  `<a>`?

CSS styles are not applied fully to an `<a>` without `href`, first one is `<pagination>` and the second one is Bootstrap 4 pagination: 

![image](https://cloud.githubusercontent.com/assets/1858678/23029216/6a298128-f472-11e6-9a5c-632eb832daa3.png)

**Comment by lokyoung** [comment]
Hello @ecmel . Thanks for the feedback. I think maybe we can add property `herf='#'` to each `a` element. I will add new PR for that.

**Comment by lokyoung** [comment]
#7

**Comment by lokyoung** [comment]
Hello @ecmel . I test it using bootstrap 4. It works ok now. You can install the latest version `0.5.0` to see what happens. Thanks.

**Comment by ecmel** [comment]
Works perfect, thanks.
