### ISSUE TITLE
Active pagination number +1 

### ISSUE THREAD

**Issue by Al3xR0** [lokyoung/vuejs-paginate#60]
My pagination number is always +1 the current number, I don't know why.

I added `this.$refs.paginate.selected = this.pagination.current_page - 1;` in order to fix this.

**Comment by reganjohnson** [comment]
The pages are stored using a 0 index array, where the first element (page 1) is at index 0.

**Comment by lokyoung** [comment]
@Al3xR0 Just like @reganjohnson mentioned, we are using array index. So you need to `-1` at your current number. Hope it solve your issue.
@reganjohnson Thanks!
