### ISSUE TITLE
Add 'Last' & 'First' buttons (Suggestion)

### ISSUE THREAD

**Issue by HakamFostok** [lokyoung/vuejs-paginate#61]
Just a suggestion.
Why not add 'Last' and 'First' button, and make them configurable, so the client could activate or deactivate them?

**Comment by lokyoung** [comment]
@HakamFostok Thanks for the advice. I will add it in next version.

**Comment by jusdeleon** [comment]
Hi, I forked the project and did this functionality. It's not configurable though, and it seems that I broke the tests, so I haven't made a PR. If you're interested, here's the commit:

https://github.com/jusdeleon/vuejs-paginate/commit/e5539faa9f63c2463c286f966221cf5affe3a22b

**Comment by lokyoung** [comment]
Hi @HakamFostok @jusdeleon . Sorry for the delay, I have published a new release `v1.6.0`. Now you can add these buttons by add prop `first-last-button`.
```
<paginate
  :page-count="10"
  :first-last-button="true">
</paginate>
```
You can also custom the content of them by `first-button-text` and `last-button-text`. Any questions you can reopen this issue. Thanks.

**Comment by subzero101** [comment]
With say 10 pages, when clicking 'first' and 'last' the page numbers 0 and 9 are returned respectively. I would have expected 1 and 10 as when clicking the actual page numbers. Is this intended behavior?

**Comment by lokyoung** [comment]
Hi @subzero101 . We are returning the index of the page, just like in an array. So 0 and 9 are returned. Thanks.
