### ISSUE TITLE
How I can change active page through methods?

### ISSUE THREAD

**Issue by Falcornus** [lokyoung/vuejs-paginate#62]
I need to change the active page after I receive the data. How I can do it? Because it seems that `v-model` doesn't work this way

**Comment by Falcornus** [comment]
I resolved this problem through `force-page` property and `click-handler` . 

And thanks for your plugin :)

**Comment by lokyoung** [comment]
@Falcornus Hope you will like this plugin. Any questions please feel free to let me know. Thanks.
