### ISSUE TITLE
如何实现在一个页面中有2个不同的分页，他们互不影响。

### ISSUE THREAD

**Issue by fengwei1314** [lokyoung/vuejs-paginate#70]
我是通过这种方式，新手求帮助!
Vue.component('paginate', VuejsPaginate);

`pagination: new Vue({
                el: '#casePagination',
                template: '<paginate :pageCount="totalPage" :containerClass="\'pagination\'" :pageClass ="\'page-item\'" :pageLinkClass ="\'page-link\'" :prevText="\'上一页\'" :nextText="\'下一页\'" ' +
                           ':prevClass="\'page-item\'" :nextClass="\'page-item\'" :prevLinkClass="\'page-link\'" :nextLinkClass="\'page-link\'" :clickHandler="clickCallback"></paginate>',
                data: {
                    totalPage: 0
                },
                methods: {
                    clickCallback: function (page) {                      
                    }
                }
            }),`

**Comment by lokyoung** [comment]
@fengwei1314 直接在模板中添加就行
```html
<paginate
  :page-count="20"
  :click-handler="functionName"
  :prev-text="'Prev'"
  :next-text="'Next'"
  :container-class="'className'">
</paginate>

<paginate
  :page-count="20"
  :click-handler="functionName"
  :prev-text="'Prev'"
  :next-text="'Next'"
  :container-class="'className'">
</paginate>
```
