### ISSUE TITLE
active-class in anchor tag

### ISSUE THREAD

**Issue by william-jay** [lokyoung/vuejs-paginate#73]
how to put active class in anchor tag? the default active-class is put in the li tag
I want to be like this

`<ul class="pagination">`
       `<li><a class="pagination-link is-current"> 1 </a> </li>`
        `<li><a class="pagination-link"> 2 </a> </li>`
         `<li><a class="pagination-link"> 3 </a> </li>`
`</ul>`

**Comment by william-jay** [comment]
any help?

**Comment by MirkoManojlovic** [comment]
I had the same issue and I found that if you put **no-li-surround** prop to true, active class will be set on anchor tag instead of list tag.

Code:

```
<template>
	<paginate
		:page-count="20"
		:page-range="3"
		:margin-pages="2"
		:click-handler="clickCallback"
		:prev-text="'Prev'"
		:next-text="'Next'"
		:container-class="'pagination'"
		:page-class="'page-item'"
		:no-li-surround="true">
	</paginate>
</template>
```

Hope this helps you :)

Cheers

**Comment by lokyoung** [comment]
@william-jay You can try `no-li-surround`. Hope it helps you.
@MirkoManojlovic Thanks.
