### ISSUE TITLE
Error 'TypeError: e._v is not a function' when trying to load component

### ISSUE THREAD

**Issue by devloe** [lokyoung/vuejs-paginate#77]
I'm getting `TypeError: e._v is not a function`.

vue-js-paginate v. 1.8.0.
Vue v. 2.1.0.

Any toughts?

**Comment by lokyoung** [comment]
Hi @devloe . Could you please upgrade your `Vue` version to have a try. Or could you please provide any online demo like [this](https://jsfiddle.net/lokyoung/u3u3nzns/) ?

**Comment by lokyoung** [comment]
Hi @devloe . I will close this issue for now. Any questions just feel free to ask. Thanks.
