### ISSUE TITLE
Property Defaults

### ISSUE THREAD

**Issue by ecmel** [lokyoung/vuejs-paginate#8]
I suggest the following property defaults from Bootstrap 4:

```
<paginate 
    containerClass="pagination" 
    pageClass="page-item"
    pageLinkClass="page-link" 
    prevText="«" 
    prevClass="page-item" 
    prevLinkClass="page-link" 
    nextText="»" 
    nextClass="page-item"
    nextLinkClass="page-link"
</paginate>
```

**Comment by lokyoung** [comment]
Hello @ecmel . Thanks for the feedback! It's a good idea. But not sure if there are some users don't want to use the style of Bootstrap. If i set the default property. They need to change and set each on of them to other style. So i think maybe the Bootstrap 4 is better for you and me. But not so appropriate for some users. Could you agree?

**Comment by ecmel** [comment]
Hi @lokyoung in any case `containerClass` should be set and `ul` `li` and `a` should have styles under `containerClass`.

People using other CSS frameworks will have to set all styles anyway.

**Comment by lokyoung** [comment]
Thanks @ecmel . Please just leave the style with empty default value.  I don't think it's a good behavior to set the default value as bootstrap 4 style.

**Comment by ecmel** [comment]
Thanks @lokyoung
