### ISSUE TITLE
hide-prev-next is not working

### ISSUE THREAD

**Issue by getsetbro** [lokyoung/vuejs-paginate#82]
:hide-prev-next="true" is not working for me so I am using `:next-class="'d-none'" :prev-class="'d-none'"` with bootstrap 4.
Version: vuejs-paginate@1.9.3
Browser: latest chrome: Version 67.0.3396.79 (Official Build) (64-bit)
OS: Windows 10 with latest updates

**Comment by lokyoung** [comment]
Hi @getsetbro . You can found the description of `hide-prev-next` in the documentation. `Hide prev/next button when there is no previous or next page. `. Any further questions please feel free to ask. Thanks.
