### ISSUE TITLE
Active page not changing

### ISSUE THREAD

**Issue by srv91** [lokyoung/vuejs-paginate#91]
Hi, I just started to face this issue of active page not changing. Cross checked with your demo and even that's broken. Could you please check and update?
Many thanks!

**Comment by lokyoung** [comment]
Hi @srv91 . You can solve this issue by passing a `v-model` for now or use the `1.x` version. I will try to find it i can make it work well without `v-model`. Thanks and sorry for the late response.

**Comment by jacobgoh101** [comment]
`v-model` didn't work for me.

But using `force-page` in version [1.9.5](https://www.npmjs.com/package/vuejs-paginate/v/1.9.5) works.

**Comment by Gnoq** [comment]
I found it: #85 

Thanks!

**Comment by lokyoung** [comment]
Hi @Gnoq @srv91 . You can try `v2.1.0`. Now you can change the active page without binding `v-model`. Thanks.
