### ISSUE TITLE
Negative currentPage value

### ISSUE THREAD

**Issue by blyleven** [lokyoung/vuejs-paginate#92]
Hi there, 

Thanks for this great package, really love it!

I'm using this with a search query, which works great except when the array of results is empty. When there are no results after searching no pagination is shown (which is correct), but when I change my search query and the array of results is filled again, the computed currentPage value is stuck at -1. 

I think this should be reset to 1 when the value hits a negative value. Is there someway I can do this?

Thanks!

**Comment by xlcrr** [comment]
I have the same problem. Did you find a solution?
