### ISSUE TITLE
How to use it with my own table

### ISSUE THREAD

**Issue by allaghi** [lokyoung/vuejs-paginate#93]
Hello everyone,
I am wondering how I can apply vuejs-paginate with my own table.
many thanks &  best regards

**Comment by lokyoung** [comment]
Hi @allaghi , just not sure what is your question exactly is. You can just simply add it to your table and pass the related data to the paginate component.

**Comment by lokyoung** [comment]
@allaghi I will close this issue for now. Any questions please reopen it. Thanks.
