### ISSUE TITLE
Registering component

### ISSUE THREAD

**Issue by shiibbyy** [lokyoung/vuejs-paginate#94]
Hi, new to Vue and not quite sure on how to get this working.

I use ES6 and have gone ahead and imported into a "pagination.vue" file by using the - 

> import Paginate from 'vuejs-paginate'

but not sure how I would go about adding in the "Vue.component('paginate', Paginate)" (as in, how do i enter it into my code? I am working on a basic, existing page with template, script, style. Just not sure if it goes into a method, or data or somewhere else completely?

Thanks!

**Comment by lokyoung** [comment]
@shiibbyy You can check the demo in this repo. Thanks!
https://github.com/lokyoung/vuejs-paginate/blob/master/demo/demo.js
