### ISSUE TITLE
Container class doesn't initialized in production

### ISSUE THREAD

**Issue by mrlee23** [lokyoung/vuejs-paginate#96]
Hello, Thank you for the providing a convenient pagination package.

When I use a vuejs-paginate with Nuxt.js and Materilize.css in my project, I found a rendering bug.

I set the vuejs-paginate props like this : 
```js
<vuejs-paginate
  v-model="currentPage"
  :page-count="getPageCount()"
  :page-range="pageRange"
  :margin-pages="1"
  :container-class="'pagination'"
  :page-class="'waves-effect waves-light'"
  :active-class="'active teal'"
  :page-link-class="'page-link'"
  :prev-class="'waves-effect waves-light'"
  :next-class="'waves-effect waves-light'"
  :prev-text="prevText"
  :next-text="nextText"
  :click-handler="click"
  >
```

In development status, It works fine.
But, In production status, vuejs-paginate doesn't bind the `container-class` as a class name.
However, after click event, added a container class name and works fine.

**Initialized page :**

<img width="121" alt="2018-10-29 7 37 55" src="https://user-images.githubusercontent.com/6349609/47645606-e0fbe180-dbb4-11e8-952b-f90b7d0eecb4.png">

<img width="338" alt="2018-10-29 7 37 59" src="https://user-images.githubusercontent.com/6349609/47645749-3fc15b00-dbb5-11e8-898b-eb7ba928654c.png">

**After click event :**

<img width="178" alt="2018-10-29 7 38 05" src="https://user-images.githubusercontent.com/6349609/47645618-e9541c80-dbb4-11e8-988c-21678a6d3618.png">

<img width="340" alt="2018-10-29 7 38 10" src="https://user-images.githubusercontent.com/6349609/47645753-42bc4b80-dbb5-11e8-9e5c-64648e80f768.png">

So, I bind a new `class` prop with empty string "''", It works fine. Is there any other way?

```js
<vuejs-paginate
  v-model="currentPage"
  :page-count="getPageCount()"
  :page-range="pageRange"
  :margin-pages="1"
  :container-class="'pagination'"
  :page-class="'waves-effect waves-light'"
  :active-class="'active teal'"
  :page-link-class="'page-link'"
  :prev-class="'waves-effect waves-light'"
  :next-class="'waves-effect waves-light'"
  :prev-text="prevText"
  :next-text="nextText"
  :click-handler="click"
  :class="''"
  >
```

**Comment by lokyoung** [comment]
Hi @mrlee23 , you need to setup this component by configuring nuxt.
```js
// plugins/vuejs-pagiante
import Vue from 'vue'
import Paginate from 'vuejs-paginate/src/components/Paginate.vue';
Vue.component('Paginate', Paginate);

// nuxt.config.js
module.exports = {
  plugins: [{
    src: '~/plugins/vuejs-paginate.js',
    ssr: true
  }]
}
```

**Comment by lokyoung** [comment]
@mrlee23 BTW, so sorry for replying so late since I'm too busy. I will try to reply quickly next time.
