### ISSUE TITLE
Disabling the component

### ISSUE THREAD

**Issue by elciok** [lokyoung/vuejs-paginate#98]
When I click a page number, I would like to disable all links inside the component while data for the page that was selected is being fetched. Currently, there is no way to do that.

I was thinking something like a Boolean property named "disabled" that could be set to true when you want to disable the whole component.

What do you think? I could work on a PR for that if you think this should be added to your project.

**Comment by lokyoung** [comment]
Hi @elciok . I'm afraid it's not a general requirement and it's not this component should concern. You can do this like the following.
```html
<div v-bind:class="{ loading: loading }">
  <paginate
    :page-count="20">
  </paginate>
</div>
```
